---
output: 
  md_document:
    variant: markdown_github
---

## Transparencias del trabajo en equipo de la asignatura "Big Data"

<!-- El párrafo de abajo has de dejarlo tal cual. NO HAS DE CAMBIAR NADA!!-->

Repo utilizado para elaborar las transparencias del trabajo en equipo para la asignatura "Programación y manejo de datos en la era del Big Data" de la Universitat de València durante el curso 2021-2022. La página web de la asignatura puede verse aquí: <https://perezp44.github.io/intro-ds-20-21-web/>.

<!-- En la linea de abajo TIENES QUE SUSTITUIR "perezp44" por tu usuario de Github-->

La versión final de estas transparencias puede visualizarse en: <https://paupiera23.github.io/_trabajo_BigData_slides/>.


<!-- En la linea de abajo TIENES QUE SUSTITUIR (otra vez) "perezp44" por tu usuario de Github-->

La versión final del trabajo puede visualizarse en: <https://paupiera23.github.io/_trabajo_BigData_equipo/>.



<!-- Abajo podéis escribir lo que queráis, igual un resumen del trabajo, o ..., o ... pero al menos, tenéis que poner el título del trabajo y el nombre de los componentes del equipo-->

El título del trabajo es Sistema de Pensiones Español.  En el trabajo haremos un análisis de las variables que afectan al sistema de pensiones asi como su evolución y una comparativa con otros sistemas. A día de hoy hemos pensado en realizar un análisis de la evolución que ha tenido nuestro sistema de pensiones. Para ello el eje del trabajo girará en torno a tres grandes variables: la demografía (edad media, tasa de mortalidad, esperanza de vida...), el mercado de trabajo y otros sistemas alternativos. Además, intentaremos realizar una proyección tanto de la evolución del sistema de pensiones como del mercado laboral como de los otros sistemas que analizaremos.

Para la realización de nuestro trabajo tenemos pensado sacar los datos del INE, arreglarlos y realizar los análisis gráficos correspondientes. 


<!-- Finalmente, acuérdate que cuando hayas hecho los cambios y hayas dejado este archivo como hayáis decidido, TENEIS que knittearlo para que los cambios se actualicen en el fichero Readme.md, que es el que finalmente se visualizará en Github-->


